In [58]:
import torch
import torch.nn as nn

# 예시 데이터
batch_size = 4  # 배치 크기
num_events = 9  # 이벤트 개수


In [67]:
# 모델 출력과 레이블 생성
model_output = torch.rand(batch_size, num_events)  # 모델 출력 (0~1 사이의 랜덤 값)
labels = torch.randint(0, 2, (batch_size, num_events)).float()  # 레이블 (0 또는 1)

print(model_output)
print(labels)

tensor([[0.4217, 0.8092, 0.0341, 0.5127, 0.7009, 0.6083, 0.3927, 0.3558, 0.8781],
        [0.3614, 0.9641, 0.2632, 0.7411, 0.1855, 0.0049, 0.9723, 0.7857, 0.0312],
        [0.2760, 0.8210, 0.3146, 0.5538, 0.1929, 0.9110, 0.5147, 0.2747, 0.7482],
        [0.7167, 0.3775, 0.7702, 0.5664, 0.6772, 0.7467, 0.6182, 0.0252, 0.7397]])
tensor([[0., 0., 0., 0., 0., 0., 1., 1., 0.],
        [0., 0., 0., 0., 1., 0., 1., 1., 0.],
        [0., 0., 0., 1., 0., 1., 0., 0., 0.],
        [0., 1., 1., 1., 0., 1., 0., 0., 1.]])


In [68]:
# 가중치 생성 (각 이벤트 별로 다른 가중치 부여)
weights = torch.rand(num_events)  # 가중치 (0~1 사이의 랜덤 값)
print(weights)

tensor([0.4789, 0.3218, 0.4851, 0.7658, 0.1595, 0.8769, 0.5706, 0.9301, 0.4311])


In [69]:
# BCE Loss 계산
criterion = nn.BCELoss(weight=weights, reduction="mean")  # Binary Cross Entropy Loss 객체 생성
loss = criterion(model_output, labels)  # 모델 출력과 레이블로 손실 계산

print(loss.item())

0.36551424860954285


In [70]:
y_hat_bin = (model_output > 0.5).type(torch.int32)
print(y_hat_bin)

tensor([[0, 1, 0, 1, 1, 1, 0, 0, 1],
        [0, 1, 0, 1, 0, 0, 1, 1, 0],
        [0, 1, 0, 1, 0, 1, 1, 0, 1],
        [1, 0, 1, 1, 1, 1, 1, 0, 1]], dtype=torch.int32)


In [78]:
(y_hat_bin == labels).sum(dim=0)[1].item()

0

In [81]:
confusion_vector = y_hat_bin / labels
print(confusion_vector)
print(confusion_vector[:,2])

tensor([[nan, inf, nan, inf, inf, inf, 0., 0., inf],
        [nan, inf, nan, inf, 0., nan, 1., 1., nan],
        [nan, inf, nan, 1., nan, 1., inf, nan, inf],
        [inf, 0., 1., 1., inf, 1., inf, nan, 1.]])
tensor([nan, nan, nan, 1.])


In [83]:
torch.sum(confusion_vector[:,2] == 1).item()

1